OficinaMecanica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('OrdemServico.urls')),
]

OrdemServico/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('pecas/', views.pecas, name='pecas'),
    path('addpecas/', views.addpecas, name='addpecas'),
    path('clientes/', views.clientes, name='clientes'),
    path('addclientes/', views.addclientes, name='addclientes'),
    path('mecanicos/', views.mecanicos, name='mecanicos'),
    path('addmecanicos/', views.addmecanicos, name='addmecanicos'),
    path('veiculos/', views.veiculos, name='veiculos'),
    path('addveiculos/', views.addveiculos, name='addveiculos'),
    path('equipes/', views.equipes, name='equipes'),
    path('addequipes/', views.addequipes, name='addequipes'),
    path('addordemservico/', views.addordemservico, name='addordemservico'),
    path('listaordensservico/', views.listaordensservico, name='listaordensservico'),
    path('logout/', views.logout, name='logout')
]

OrdemServico/models.py
from django.db import models

class Admin(models.Model):
    email = models.CharField(max_length=50, unique=True)
    senha = models.CharField(max_length=255)
    cpf = models.CharField(max_length=50)
    codigoAdmin = models.CharField(max_length=255)

    class Meta:
        db_table = 'admin'

class Cliente(models.Model):
    nome = models.CharField(max_length=45)
    email = models.CharField(max_length=50)
    telefone = models.IntegerField()
    cpf = models.CharField(max_length=45)
    endereco = models.CharField(max_length=100)

    class Meta:
        db_table = 'cliente'

class Mecanico(models.Model):
    nome = models.CharField(max_length=45)
    cpf = models.CharField(max_length=45)
    especialidade = models.CharField(max_length=100)
    endereco = models.CharField(max_length=100)
    email = models.CharField(max_length=50)
    telefone = models.CharField(max_length=20)

    class Meta:
        db_table = 'mecanico'

    def __str__(self):
        return self.nome

class Pecas(models.Model):
    nome = models.CharField(max_length=45)
    marca = models.CharField(max_length=50)
    preco = models.FloatField()
    quantidade = models.IntegerField()

    class Meta:
        db_table = 'pecas'

class Veiculo(models.Model):
    nome = models.CharField(max_length=45)
    marca = models.CharField(max_length=45)
    cor = models.CharField(max_length=45)
    placa = models.CharField(max_length=45)
    modelo = models.CharField(max_length=45)

    class Meta:
        db_table = 'veiculo'

class Equipe(models.Model):
    nome = models.CharField(max_length=45)
    descricao = models.CharField(max_length=50)
    especialidade = models.CharField(max_length=45)
    mecanicos = models.ManyToManyField(Mecanico)

    class Meta:
        db_table = 'equipe'

    def __str__(self):
        return self.nome

    @classmethod
    def create_default_equipe(cls, equipe_id=None):
        if equipe_id:
            equipe_padrao, _ = cls.objects.get_or_create(id=equipe_id)
        else:
            equipe_padrao, _ = cls.objects.get_or_create(
                nome='Equipe Padrão',
                descricao='Descrição da Equipe Padrão',
                especialidade='Especialidade Padrão'
            )
        return equipe_padrao

class OrdemServico(models.Model):
    dataEmissao = models.DateTimeField()
    dataConclusao = models.DateTimeField(null=True)
    valor = models.FloatField()
    descricao = models.TextField()
    status = models.CharField(max_length=20, choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')])
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    equipe = models.ForeignKey(Equipe, on_delete=models.CASCADE, default=Equipe.create_default_equipe, related_name='ordens_servico')

    class Meta:
        db_table = 'ordem_servico'

class PecasOrdemServico(models.Model):
    pecas = models.ForeignKey(Pecas, on_delete=models.CASCADE)
    ordem_servico = models.ForeignKey(OrdemServico, on_delete=models.CASCADE)
    quantidade = models.IntegerField(default=1)

    class Meta:
        db_table = 'pecas_ordem_servico'

    @classmethod
    def get_default_peca_id(cls):
        default_peca = Pecas.objects.get(nome='Peca Padrão')
        return default_peca.id

OrdemServico/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.utils import timezone
from django import forms
from django.db import transaction
import datetime
import json

from .models import Admin
from .models import Cliente
from .models import Mecanico
from .models import Pecas
from .models import Veiculo
from .models import Equipe
from .models import OrdemServico
from .models import PecasOrdemServico

def login (request):
    if request.method == "GET":
        return render(request, 'login.html')
    else:
        email = request.POST['email']
        senha = request.POST['senha']
        try:
            admin = Admin.objects.get(email=email)
            if admin.senha == senha:
                return render(request, 'home.html')
            else:
                return render(request, 'login.html', {'erro': 'Senha incorreta'})
        except Admin.DoesNotExist:
            return render(request, 'login.html', {'erro': 'Usuário não encontrado'})

def home (request):
    if request.method == "GET": 
        return render(request, 'home.html')

def pecas(request):
    pecas = Pecas.objects.all()
    return render(request, 'listaPecas.html', {'pecas': pecas})

def addpecas(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        marca = request.POST.get('marca')
        preco = request.POST.get('preco')
        quantidade = request.POST.get('quantidade')

        peca = Pecas(nome=nome, marca=marca, preco=preco, quantidade=quantidade)
        peca.save()

        return redirect('pecas')

    return render(request, 'addPeca.html')

def clientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'listaClientes.html', {'clientes': clientes})

def addclientes(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        cpf = request.POST.get('cpf')
        telefone = request.POST.get('telefone')
        endereco = request.POST.get('endereco')

        cliente = Cliente(nome=nome, email=email, cpf=cpf, telefone=telefone, endereco=endereco)
        cliente.save()

        return redirect('clientes')

    return render(request, 'addCliente.html')

def mecanicos(request):
    mecanicos = Mecanico.objects.all()
    return render(request, 'listaMecanicos.html', {'mecanicos': mecanicos})

def addmecanicos(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        cpf = request.POST.get('cpf')
        especialidade = request.POST.get('especialidade')
        endereco = request.POST.get('endereco')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')

        mecanico = Mecanico(nome=nome, cpf=cpf, especialidade=especialidade, endereco=endereco, email=email, telefone=telefone)
        mecanico.save()

        return redirect('mecanicos')

    return render(request, 'addMecanico.html')

def veiculos(request):
    veiculos = Veiculo.objects.all()
    return render(request, 'listaVeiculos.html', {'veiculos': veiculos})

def addveiculos(request):
    if request.method == 'POST':
        nome = request.POST.get('nome')
        marca = request.POST.get('marca')
        cor = request.POST.get('cor')
        placa = request.POST.get('placa')
        modelo = request.POST.get('modelo')

        veiculo = Veiculo(nome=nome, marca=marca, cor=cor, placa=placa, modelo=modelo)
        veiculo.save()

        return redirect('veiculos') 

    return render(request, 'addVeiculo.html')

def equipes(request):
    equipes = Equipe.objects.all()
    return render(request, 'listaEquipes.html', {'equipes': equipes})

def addequipes(request):
    if request.method == 'POST':
        nome = request.POST['nome']
        descricao = request.POST['descricao']
        especialidade = request.POST['especialidade']
        mecanicos_ids = [int(id) for id in request.POST.getlist('mecanicos') if id]

        equipe = Equipe(nome=nome, descricao=descricao, especialidade=especialidade)
        equipe.save()
        equipe.mecanicos.set(mecanicos_ids)  # Adicionar mecânicos à equipe

        return redirect('equipes')

    mecanicos = Mecanico.objects.all()
    return render(request, 'addEquipe.html', {'mecanicos': mecanicos})

def addordemservico(request):
    equipes = Equipe.objects.all()
    pecas = Pecas.objects.all()

    if request.method == 'POST':
        try:
            # Obter dados do formulário
            placa = request.POST.get('placa')
            nome_cliente = request.POST.get('nome_cliente')
            modelo_carro = request.POST.get('modelo_carro')
            cor_carro = request.POST.get('cor_carro')
            problema = request.POST.get('problema')
            data_entrada = request.POST.get('data_entrada')
            data_prevista = request.POST.get('data_prevista')
            equipe_id = request.POST.get('equipe')
            preco_total = request.POST.get('preco_total')
            pecas_data = request.POST.get('pecas_json')
            pecas_data = json.loads(pecas_data)
            mecanicos_ids = request.POST.getlist('mecanicos')

            # Convertendo strings para os tipos de dados apropriados
            data_entrada = timezone.datetime.strptime(data_entrada, "%Y-%m-%dT%H:%M")
            data_prevista = timezone.datetime.strptime(data_prevista, "%Y-%m-%dT%H:%M")

            # Criar o cliente (ou obter se já existir com o mesmo nome)
            cliente, created = Cliente.objects.get_or_create(
                nome=nome_cliente,
                defaults={'email': 'default@email.com', 'telefone': '123456789', 'cpf': '12345678901', 'endereco': 'Endereço padrão'}
            )

            # Tratar o preço total
            preco_total = float(preco_total) if preco_total and preco_total != '' else 0.0

            # Criar o veículo associado ao cliente (ou obter se já existir com a mesma placa)
            veiculo, created = Veiculo.objects.get_or_create(
                placa=placa,
                defaults={'cliente': cliente, 'modelo': modelo_carro, 'cor': cor_carro}
            )

            # Obter a equipe selecionada
            equipe = Equipe.objects.get(id=equipe_id)

            # Obter a lista de peças selecionadas
            pecas_ids = [item['id'] for item in pecas_data]
            pecas_selecionadas = Pecas.objects.filter(id__in=[int(item) for item in pecas_ids])

            # Usar uma transação para garantir que as operações no banco de dados sejam atômicas
            with transaction.atomic():
                # Criar a ordem de serviço
                ordem_servico = OrdemServico(
                    dataEmissao=timezone.now(),
                    dataConclusao=data_prevista,
                    valor=preco_total,
                    descricao=problema,
                    status='pendente',
                    veiculo=veiculo,
                )
                
                ordem_servico.cliente = cliente
                ordem_servico.equipe = equipe 

                ordem_servico.save()

                # Criar as relações entre peças e ordem de serviço usando o modelo PecasOrdemServico
                for peca in pecas_selecionadas:
                    PecasOrdemServico.objects.create(pecas=peca, ordem_servico=ordem_servico)

            print("Ordem de Serviço criada com sucesso:", ordem_servico.id)
            return redirect('listaordensservico')

        except Equipe.DoesNotExist:
            raise Http404("A equipe especificada não existe.")
        except Pecas.DoesNotExist:
            raise Http404("Uma ou mais peças especificadas não existem.")

    return render(request, 'addOrdemServico.html', {'equipes': equipes, 'pecas': pecas})

def listaordensservico(request):
    ordens_servico = OrdemServico.objects.all()
    return render(request, 'listaOrdensServico.html', {'ordens_servico': ordens_servico})

def logout(request):
    return redirect('login')

OrdemServico/templates/addCliente.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'addCliente/css/addCliente.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Inicio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Peças
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'pecas' %}">Lista de Peças</a></li>
                            <li><a class="dropdown-item" href="{% url 'addpecas' %}">Adicionar Peças</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Clientes
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'clientes' %}">Lista de Clientes</a></li>
                            <li><a class="dropdown-item" href="{% url 'addclientes' %}">Adicionar Clientes</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Mecânicos
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'mecanicos' %}">Lista de Mecânicos</a></li>
                            <li><a class="dropdown-item" href="{% url 'addmecanicos' %}">Adicionar Mecânicos</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Veículos
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'veiculos' %}">Lista de Veículos</a></li>
                            <li><a class="dropdown-item" href="{% url 'addveiculos' %}">Adicionar Veículos</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Equipes
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'equipes' %}">Lista de Equipes</a></li>
                            <li><a class="dropdown-item" href="{% url 'addequipes' %}">Adicionar Equipe</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Serviços
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'listaordensservico' %}">Lista de Serviços</a></li>
                            <li><a class="dropdown-item" href="{% url 'addordemservico' %}">Adicionar Serviços</a>
                            </li>
                        </ul>
                    </li>
                    <button type="button" class="btn"><a href="{% url 'logout' %}" class="btnLogout">Logout</a></button>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="title" >Adicionar Clientes</h1>
            </div>
        </div>
        <div class="row">
            <form action="{% url 'addclientes' %}" method="POST">{% csrf_token %}
                <label for="id_nome" class="form-label">Nome</label>
                <input class="form-control" type="text" name="nome" id="id_nome" placeholder="Informe o nome" required>
                <br>
                <label for="id_email" class="form-label">Email</label>
                <input class="form-control" type="text" name="email" id="id_email" placeholder="Informe o email" required>
                <br>
                <label for="id_endereco" class="form-label">Endereço</label>
                <input class="form-control" type="text" name="endereco" id="id_endereco" placeholder="Informe o endereco" required>
                <br>
                <label for="id_telefone" class="form-label">Telefone</label>
                <input class="form-control" type="number" name="telefone" id="id_telefone" placeholder="Informe o telefone" required>
                <br>
                <label for="id_cpf" class="form-label">CPF</label>
                <input class="form-control" type="text" name="cpf" id="id_cpf" placeholder="Informe o cpf" required>
                <br>
                <button type="submit" class="btn btn-primary btnAddCliente">Adicionar Cliente</button>
            </form>
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</html>

OrdemServico/templates/addMecanico.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'addMecanico/css/addMecanico.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Inicio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Peças
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'pecas' %}">Lista de Peças</a></li>
                            <li><a class="dropdown-item" href="{% url 'addpecas' %}">Adicionar Peças</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Clientes
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'clientes' %}">Lista de Clientes</a></li>
                            <li><a class="dropdown-item" href="{% url 'addclientes' %}">Adicionar Clientes</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Mecânicos
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'mecanicos' %}">Lista de Mecânicos</a></li>
                            <li><a class="dropdown-item" href="{% url 'addmecanicos' %}">Adicionar Mecânicos</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Veículos
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'veiculos' %}">Lista de Veículos</a></li>
                            <li><a class="dropdown-item" href="{% url 'addveiculos' %}">Adicionar Veículos</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Equipes
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'equipes' %}">Lista de Equipes</a></li>
                            <li><a class="dropdown-item" href="{% url 'addequipes' %}">Adicionar Equipe</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown drop">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Serviços
                        </a>
                        <ul class="dropdown-menu menu">
                            <li><a class="dropdown-item" href="{% url 'listaordensservico' %}">Lista de Serviços</a></li>
                            <li><a class="dropdown-item" href="{% url 'addordemservico' %}">Adicionar Serviços</a>
                            </li>
                        </ul>
                    </li>
                    <button type="button" class="btn"><a href="{% url 'logout' %}" class="btnLogout">Logout</a></button>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1 class="title">Adicionar Mecânico</h1>
            </div>
        </div>
        <div class="row">
            <form action="{% url 'addmecanicos' %}" method="POST">{% csrf_token %}
                <label for="id_nome" class="form-label">Nome</label>
                <input class="form-control" type="text" name="nome" id="id_nome" placeholder="Informe o nome" required>
                <br>
                <label for="id_email" class="form-label">Email</label>
                <input class="form-control" type="text" name="email" id="id_email" placeholder="Informe o email" required>
                <br>
                <label for="id_especialidade" class="form-label">Especialidade</label>
                <input class="form-control" type="text" name="especialidade" id="id_especialidade" placeholder="Informe a Especialidade" required>
                <br>
                <label for="id_endereco" class="form-label">Endereço</label>
                <input class="form-control" type="text" name="endereco" id="id_endereco" placeholder="Informe o endereco" required>
                <br>
                <label for="id_telefone" class="form-label">Telefone</label>
                <input class="form-control" type="number" name="telefone" id="id_telefone" placeholder="Informe o telefone" required>
                <br>
                <label for="id_cpf" class="form-label">CPF</label>
                <input class="form-control" type="text" name="cpf" id="id_cpf" placeholder="Informe o cpf" required>
                <br>
                <button type="submit" class="btn btn-primary btnAddMecanico">Adicionar Mecânico</button>
            </form>
        </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</html>

OrdemServico/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'login/css/login.css' %}">        
</head>

<body>
    <div class="container">
            <div class="row">
                <div class="ImgLogo">
                    <img src="{% static 'login/img/logo.png' %}" alt="" id="logo">
                </div>
            </div>
            <div class="row">
                <form action="{% url 'login' %}" method="POST">{% csrf_token %}
                    <div class="row">
                        <div class="mb-3">
                            <label for="exampleFormControlInput1" class="form-label">Email</label>
                            <input type="text" name="email" class="form-control" id="exampleFormControlInput1"
                                placeholder="name@example.com">
                        </div>
                    </div>
                    <div class="row">
                        <label for="inputPassword5" class="form-label">Senha</label>
                        <input type="password" name="senha" id="inputPassword5" class="form-control"
                            aria-describedby="passwordHelpBlock">
                    </div>
                    <div class="row">
                        <div class="col-auto">
                            <button type="submit" class="btn btn-primary mb-3" id="btnEntrar">Confirmar</button>
                        </div>
                    </div>
                </form>
            </div>
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</html>